version: '3'

volumes:
  pgdata:

services:

  hotel:
    build: web/
    container_name: hotel-service
    ports:
      - "8080:8080"
    links:
      - db

  db:
    image: postgres
    container_name: db-service
    ports:
      - "5431:5432"
    hostname: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=netcracker_hotel
    volumes:
      - pgdata:/var/lib/postgresql/data