spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/hotel_bussines
    password: Lizakapusta377
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: false
      generate-ddl: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false

